### ISSUE TITLE
僅能搜尋一次

### ISSUE THREAD

**Issue by tedlu-tw** [Open-Edu-Tw/courseapi-fe-solid#2]
搜尋時，僅會出現第一個關鍵字，後續關鍵字皆不會反映在搜尋結果（但頂端與 title 會呈現）
解析度 1920*1080
作業系統 Windows
瀏覽器 Firefox

https://user-images.githubusercontent.com/49829569/185796800-ee66c933-c8cb-4a50-bef6-1d5c2dd0bfb9.mp4

**Comment by pan93412** [comment]
就還沒開發完成不要這麼急著提 bug ====

**Comment by tedlu-tw** [comment]
先提，不一定要現在修，而是因為搜尋這個部分即使開發完，也有機會沒注意到，先提出，之後可注意。我目前也只看到這兩個 bug。
